services:
  statikserve:
    image: ghcr.io/xoconoch/statikserve

    # arbitrary non-root UID
    user: "${UID:-1000}:0"

    ports:
      - "80:8081"

    environment:
      AUTH_TOKEN: your_secret_token

    volumes:
      - ./site:/var/www/site

    security_opt:
      - no-new-privileges:true

    read_only: true

    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run/nginx

    restart: unless-stopped
